# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Short Python Intro
author: ""
logo: logo.png
copyright: "2025"  # Copyright year to be placed in the footer

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: ShortPythonIntro.tex

# Activating Thebe, thus making code cells exectuable
launch_buttons:
  thebe: true

# Information about where the book exists on the web
repository:
  url                       : https://github.com/JensLiebehenschel/ShortPythonIntro  # Online location of your book
  path_to_book              : ShortPythonIntro  # Optional path to your book, relative to the repository root
  branch                    : main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  use_directory_urls: true
  # CC-License: CC BY-NC-ND
  extra_footer: |
    Concept by Jens Liebehenschel, implemented by Edward Späth <br> No warranty of any kind. <br> <a href="https://www.frankfurt-university.de/en/about-us/faculty-2-computer-science-and-engineering/contacts-at-faculty-2/professors-at-faculty-2/jens-liebehenschel/">Prof. Dr. Jens Liebehenschel</a> <br> liebehenschel@fb2.fra-uas.de <br> +49 69 1533-3948 <br> <br> <p xmlns:cc="http://creativecommons.org/ns#" >This work is licensed under <a href="https://creativecommons.org/licenses/by-nc-nd/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/nc.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/nd.svg?ref=chooser-v1" alt=""></a></p>

sphinx:
  config:
    html_show_copyright: false